from __future__ import annotations

from typing import Protocol

from sellerbot.models import Order, OrderStatus, Product


class StoreRepository(Protocol):
    async def get_products(self) -> list[Product]: ...
    async def get_product(self, product_id: str) -> Product | None: ...
    async def count_stock(self, product_id: str) -> int: ...
    async def create_order(self, order: Order) -> None: ...
    async def get_order(self, order_id: str) -> Order | None: ...
    async def update_order_status(self, order_id: str, status: OrderStatus) -> None: ...
    async def pop_first_stock_item(self, product_id: str) -> str | None: ...
    async def get_orders_for_user(self, user_id: int) -> list[Order]: ...
    async def get_user_ids(self) -> list[int]: ...
    async def get_statistics(self) -> dict[str, int]: ...
